# Generated by Django 5.2.8 on 2025-11-24 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='id_categoria',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='id_log',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='tipo',
            field=models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='id_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cliente'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='EstoqueProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria')),
                ('id_estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estoque')),
                ('id_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.log')),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produto')),
            ],
        ),
    ]
