# Generated by Django 5.2.8 on 2025-11-28 12:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_estoque_quantidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque_minimo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='movimentedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
